### ISSUE TITLE
FTC6 prohibit DHW doesn't work

### ISSUE THREAD

**Issue by johnhoran** [gekkekoe/esphome-ecodan-hp#41]
The prohibit DHW mode doesn't seem to work, either turning it off or on.  The sensor for DHW Prohibit does work if I change the setting on the device itself.  All other settings seem to work correctly though.

**Comment by gekkekoe** [comment]
setting prohibit is only available in server control mode. see https://github.com/gekkekoe/esphome-ecodan-hp?tab=readme-ov-file#server-control--prohibit-dhwheatingcooling-enabled-by-default

**Comment by johnhoran** [comment]
Oh, thank you.
