### ISSUE TITLE
Missing Energy Delivery/Consumption & COP

### ISSUE THREAD

**Issue by Masterwork** [gekkekoe/esphome-ecodan-hp#44]
So far everything is working fine but there are no consumption and delivery and as well the COP for heating and cooling is missing.
Could you help me with that?
![IMG_1933](https://github.com/user-attachments/assets/c24fccdb-82e8-48de-a14d-0eeddf94eaa8)

**Comment by F1p** [comment]
This data is published at midnight (FTC controller time) with figures of the previous day - It is not a live counter.

**Comment by Masterwork** [comment]
Thanks a lot for the quick response!
I just setup the ESP this afternoon. You are fully right, the data was transferred at midnight.
![IMG_1935](https://github.com/user-attachments/assets/a7ea585c-f9fe-4d2e-b953-aa27fcb1eaf6)
Thank you very much!
