### ISSUE TITLE
Set dhw mode issue

### ISSUE THREAD

**Issue by Duntch144** [gekkekoe/esphome-ecodan-hp#5]
Used with ESP32 / MQTT
Set dhw mode always goes back to Off and doesn't seems to have any action. Tried with web interface and MQTT.

**Comment by gekkekoe** [comment]
Currently that field is updated from the internal status. It only works when there's DHW session active. I've disabled that connection such that you can modify it independently. It's part of a future update

**Comment by gekkekoe** [comment]
should be working correctly now
