### ISSUE TITLE
"Software Diagnosis" icon shown in FTC6

### ISSUE THREAD

**Issue by Algram** [gekkekoe/esphome-ecodan-hp#50]
Hello,

I successfully configured your project. Before I was using https://github.com/rbroker/ecodan-ha-local.

One thing I am wondering is that in the FTC6 unit it permanently shows the "Software Diagnosis" icon now.
![image](https://github.com/user-attachments/assets/1b1aae29-cb75-4860-8edf-7fc483238b69)

What does this mean and how can I deactivate this? With the `ecodan-ha-local` project this did not happen.

Thanks a lot for your work!

**Comment by F1p** [comment]
It's not software diagnosis - it's Server Control Mode, allow you to control the prohibits on DHW, Heating & Cooling

**Comment by Algram** [comment]
> It's not software diagnosis - it's Server Control Mode, allow you to control the prohibits on DHW, Heating & Cooling

Thanks! How can I disable that? If I remove out the `confs/server-control.yaml` entry from the config it does not seem to fix it.

**Comment by F1p** [comment]
> > It's not software diagnosis - it's Server Control Mode, allow you to control the prohibits on DHW, Heating & Cooling
> 
> Thanks! How can I disable that? If I remove out the `confs/server-control.yaml` entry from the config it does not seem to fix it.
> 
> EDIT: Ah, figured it out: Comment in the server control, then disable the switch in Home Assistant, then remove it again. Thanks.
> 
> @F1p Could you explain what use cases there are for the server control? Why do people use it?

You beat me to it 👍 


Server control mode is helpful in a few ways - primary is performing an "eco" on-demand hot water run.
When you transition from DHW Prohibit "On" to "Off" - the Heat Pump will run an eco hot water boost, where "Heat Now/Force" runs the heat pump at full power, reducing efficiency. 

Secondly, prohibits respond much faster than adjusting setpoints on thermostats, so if you want to create automation to run at dynamic times - removing prohibits is easier than adjusting your controller schedule.

**Comment by gekkekoe** [comment]
you can also turn off the server control switch? no need to remove it
