### ISSUE TITLE
Is there a way to manually operate the 3-way valve and pump1/2?

### ISSUE THREAD

**Issue by mharizanov** [gekkekoe/esphome-ecodan-hp#67]
Hello, as per the title: I am looking to run a de-stratification cycle on the DHW, that requires operating pump1 and the 3-way valve. I understand I can use set up SmartGrid to run the pump + additional really on the 3-way valve, but thought it would be more elegant to do it without these interventions. This function is available from the manual control on the FTC6 control pannel, so I thought maybe it could be activated through a serial code. Thanks

**Comment by F1p** [comment]
Is de-stratification known in FTC6 as dry-up?

**Comment by mharizanov** [comment]
> Is de-stratification known in FTC6 as dry-up?

No, that different. Basically my 300 l DHW tank has its electric heater element in the middle, as the heat exchanger is split around it. I use excess PV to heat it, but in reality only half of it benefits. I therefore need to run this de-stratification cycle, to equalize the whole volume's temperature

**Comment by F1p** [comment]
Do you have a picture from the controller what options you use?

**Comment by F1p** [comment]
Ah ok, the manual operation - required to power down

You can get the status of each pump, but not seen any possibility to force them via CN105.
You might look at another form of pump control external to the FTC

**Comment by mharizanov** [comment]
I was afraid I would get this exact comment :) Alright, external manipulation it is.. Thanks
