### ISSUE TITLE
Water pump 2

### ISSUE THREAD

**Issue by Duntch144** [gekkekoe/esphome-ecodan-hp#72]
Water pump 2 is part of Zone 2, should be part of Zone 1 when breaking pressure bottle is used.

**Comment by DamijanD** [comment]
What do you mean by "part of Zone 2"? I don't see any zone in `ecodan_heatpump_water_pump_2_status` ?

**Comment by gekkekoe** [comment]
@Duntch144 can you test https://github.com/gekkekoe/esphome-ecodan-hp/pull/73 and report back if it's working for you?

**Comment by gekkekoe** [comment]
https://github.com/gekkekoe/esphome-ecodan-hp/pull/73
